notifications:
  email:
    recipients:
      - lander@erlerobotics.com
    on_failure: always

matrix:
  include:
    - os: linux
      dist: bionic
      services:
        - docker
      sudo:
        - required

before_script:
 - 

script:
 - echo "Hello gym-gazebo2 2"
