notifications:
  email:
    recipients:
      - lander@erlerobotics.com
    on_failure: always

matrix:
  include:
    - os: linux
      dist: bionic
      services:
        - docker
      sudo:
        - required

before_script:
  - mkdir /tmp/gym-gazebo2
  - mv * /tmp/gym-gazebo2
  - cd ./ci

script:
 - docker build -t linter .
