name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive 
    - name: Generate Reference-FMUs Makefile
      run: cmake -S Reference-FMUs -B bin
      working-directory: FMU
    - name: Build Reference-FMUs
      run: make
      working-directory: FMU/bin
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build assembly
      run: dotnet build --configuration Release --no-restore
    - name: Test assembly
      run: dotnet test --no-restore --verbosity normal
